x-image-def: &x-image-def
  # build:
  #     context: .
  #     dockerfile: Dockerfile
  image: distributed_llama:latest
# Build with `docker build -t distributed_llama:latest .`

# TOTAL RAM USAGE 13.5 GB
services:
  llm_ubuntu_1:
    <<: *x-image-def
    container_name: distributed_llama_node_1
    tty: true
    stdin_open: true
    # ports:
    #   - "52415:52415"
    networks:
      - llm_ubuntu_cluster_network
    volumes:
      - ./models:/app/distributed-llama/models
    deploy:
      resources:
        limits:
          memory: 6.5GB

  llm_ubuntu_2:
    <<: *x-image-def
    container_name: distributed_llama_node_2
    tty: true
    stdin_open: true
    networks:
      - llm_ubuntu_cluster_network
    volumes:
      - ./models:/app/distributed-llama/models
    deploy:
      resources:
        limits:
          memory: 6GB
    command: ./dllama worker --nthreads 4

networks:
  # my_network:
  #   driver: bridge
  llm_ubuntu_cluster_network:
    name: llm_ubuntu_cluster_network
