x-image-def: &x-image-def
  # build:
  #     context: .
  #     dockerfile: Dockerfile
  image: distributed_llama:latest
# Build with `docker build -t distributed_llama:latest .`

# RAM LIMIT NOT DEFINED
services:
  llm_ubuntu_1:
    <<: *x-image-def
    container_name: distributed_llama_node_1
    tty: true
    stdin_open: true
    # ports:
    #   - "52415:52415"
    networks:
      - llm_ubuntu_cluster_network
    volumes:
      - ./models:/app/distributed-llama/models

networks:
  # my_network:
  #   driver: bridge
  llm_ubuntu_cluster_network:
    name: llm_ubuntu_cluster_network
