x-image-def: &x-image-def
  # build:
  #     context: .
  #     dockerfile: Dockerfile
  image: distributed_llama:latest
# Build with `docker build -t distributed_llama:latest .`

services:
  llm_ubuntu_1:
    <<: *x-image-def
    container_name: distributed_llama_node_1
    # volumes:
    #   - ./.dockerpi:/sdcard
    tty: true
    stdin_open: true
    # ports:
    #   - "52415:52415"
    networks:
      - llm_ubuntu_cluster_network
    volumes:
      - ./models:/app/distributed-llama/models
    deploy:
      resources:
        limits:
          memory: 8GB

  llm_ubuntu_2:
    <<: *x-image-def
    container_name: distributed_llama_node_2
    # volumes:
    #   - ./.dockerpi:/sdcard
    tty: true
    stdin_open: true
    networks:
      - llm_ubuntu_cluster_network
    volumes:
      - ./models:/app/distributed-llama/models
    deploy:
      resources:
        limits:
          memory: 8GB

networks:
  # my_network:
  #   driver: bridge
  llm_ubuntu_cluster_network:
    name: llm_ubuntu_cluster_network
